import request from "./index";

export const category = ({data, type}) => request('category/category_list', data, type);
export const user_info = ({data, type}) => request('user/user_info', data, type);
export const user_img = ({data, type}) => request('user/user_img', data, type);
export const menu_list = ({data, type}) => request('menu/list', data, type);
export const books_list = ({data, type}) => request('books/books_list', data, type);
export const six_books = ({data, type}) => request('books/six_books', data, type);
export const sider_books_list = ({data, type}) => request('books/sider_books_list', data, type);
export const bookinfo = ({data, type}) => request('books/bookinfo', data, type);
export const chapter_list = ({data, type}) => request('books/chapter_list', data, type);
export const chapter = ({data, type}) => request('books/chapter', data, type);
export const remark_list = ({data, type}) => request('remark/remark_list', data, type);
// export const upload_img = ({data, type}) => http('http://localhost:8848/author/file/upload_test', data, type);
export const recends = ({data, type}) => request('friends/recends', data, type);
export const friends_list = ({data, type}) => request('friends/friends_list', data, type);
export const group_list = ({data, type}) => request('friends/group_list', data, type);
export const chat = ({data, type}) => request('friends/chat', data, type);
export const mine_books_list = ({data, type}) => request('books/mine_books_list', data, type);
export const history = ({data, type}) => request('books/history', data, type);
export const admin_user_list = ({data, type}) => request('admin/user/user_list', data, type);
// export const rule_list = ({data, type}) => request('admin/rule/rule_list', data, type);
export const admin_books_list = ({data, type}) => request('admin/books/books_list', data, type);
export const admin_chapter_list = ({data, type}) => request('admin/books/chapter_list', data, type);
export const admin_rule_list = ({data, type}) => request('admin/rule/rule_list', data, type);
export const admin_friends_list = ({data, type}) => request('admin/friends/friends_list', data, type);
export const admin_groups_list = ({data, type}) => request('admin/group/groups_list', data, type);
export const admin_addrs_list = ({data, type}) => request('admin/addr/addrs_list', data, type);
export const admin_tags_list = ({data, type}) => request('admin/tags/tags_list', data, type);
